### model
model_name_or_path: /cache/models/loki_8B_10
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
# finetuning_type: freeze
# freeze_trainable_layers : 24
# freeze_trainable_modules: mlp
deepspeed: /workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: ToolACE
template: llama3
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 20
packing: false

### output
output_dir: /root/train_outputs/llama/ToolACE_spindle_10
logging_steps: 1
save_steps: 0.99999
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.01
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 0.1