### model
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: mlp.down_proj
lora_alpha: 2
lora_rank: 1
# finetuning_type: freeze
# freeze_trainable_layers : 24
# freeze_trainable_modules: mlp
deepspeed: /workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: reranker_continuous_filt_max7_train
template: qwen
cutoff_len: 8192
overwrite_cache: false
preprocessing_num_workers: 20
packing: true

### output
output_dir: /root/train_outputs/Qwen2.5-0.5B-Instruct/reranker_continuous_filt_max7_train/lora_r8
logging_steps: 1
save_steps: 0.99999
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 0.1